# Generated by Django 4.2.1 on 2023-05-23 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Subsections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises_app.sections')),
            ],
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('difficult', models.IntegerField()),
                ('points', models.IntegerField()),
                ('solution_exactly', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField()),
                ('advanced_level', models.BooleanField(default=False)),
                ('solution_similar', models.ManyToManyField(blank=True, to='exercises_app.exercises')),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises_app.subsections')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('correct', models.BooleanField(default=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises_app.exercises')),
            ],
        ),
    ]
